#11: Eslint updates
therungg/therun-frontend pull request #254
Opened 2024-06-15 12:38 UTC by florence-wolfe

- Updated some ESLint library versions
- Correctly configured ESLint plugins and configs
- Removed unnecessary, and unperformant plugins and configuration
  - prettier (gets run on commit hook and can be run on file save in your editor. _very_ slow in linting)
  - github (only really used for the `.then`)
- Added new configs and plugins to improve consistency and increase confidence in code:
  - `typescript-eslint` to get proper linting code on typed code
  - `eslint-plugin-react-compiler` for new rules that conform to React 19 in the future
  - `eslint-plugin-eslint-comments` to make sure we use disable comments correctly
- Adjusted a few rules here and there. Updated some, removed others, etc.
- Lots and lots of type updates
- Refactored a lot of code based on type and lint errors
- Refactored code for correct usage, for example, using Refs instead of `document.getElementById` for element references 

Closes #11

2024-06-15 13:33 UTC, zoglo commented on app/(footer)/contact/contact.tsx
> +                                <option value="">Select a category</option>
@florence-wolfe 
Could we not just removed those empty values completely?

2024-06-15 14:39 UTC, florence-wolfe commented on src/components/live/live-user-run.tsx
> -    leaderboardGameTime = null,
this wasn't being used :shrug:

2024-06-15 14:39 UTC, florence-wolfe commented on src/components/tournament/tournament-runs.tsx
> +    const [items, setItems] = useState<React.JSX.Element[]>();
technically this should be `React.ReactNode[]` but this was inferred from the callee's type

2024-06-15 14:39 UTC, florence-wolfe commented on src/components/live/recommended-stream.tsx
> +    const newComparisons: { [key: string]: Split } = {};
this is as close to getting this type to work as I could. It has a weird mismatch in its definition and usage

2024-06-15 14:39 UTC, florence-wolfe commented on src/components/marathon/send-marathon-data-button.tsx
> +    data: unknown;
add a todo to get the type

2024-06-15 14:39 UTC, florence-wolfe commented on src/components/patreon/patreon-styles.ts
> +                    WebkitTextFillColor: "transparent",
Will adding these fields cause issues? Otherwise we can cast the type of the object and omit the fields so that they return `undefined` when accessed.

2024-06-15 14:39 UTC, florence-wolfe commented on src/components/search/autocompletion.tsx
> -    const onKeyDown = (e) => {
The logic in this function is wrong. it _can't_ work just looking through its code but you can also confirm that it doesn't work as intended in the production search

2024-06-15 18:13 UTC, florence-wolfe commented on app/races/[race]/create-next-race.tsx
> +                <Button {...props} variant="primary">
if we put the variant before the `props` then the props could override it. the order of props matter like with object spreading

2024-06-15 18:14 UTC, florence-wolfe commented on src/components/live/live-user-run.tsx
>                      )}
None of the callsites are passing that prop

2024-06-15 18:15 UTC, florence-wolfe commented on src/components/errors/session.error-boundary.tsx
> -    }, [resetSession]);
Yes it's not necessary for the callback. Was explicitly called out by the lint rule

2024-06-15 18:15 UTC, florence-wolfe commented on src/actions/reset-session.action.ts
>      } catch (error) {
the `_` prefix is only to signal known unused variables to the linter and `catch()` _has_ to have a parameter in it

2024-06-15 18:17 UTC, florence-wolfe commented on app/races/stats/[game]/category-stats-list.tsx
> +        <div className="">
Will remove all unnecessary empty strings in the codebase in a future PR

2024-06-15 18:25 UTC, florence-wolfe commented on app/races/[race]/race-participant-overview.tsx
> +    //     new Date(race.startTime as string).getTime();
The only place this was used was also commented out but I left this in case it's wanted again in the future 😅 Should probably just delete both

2024-06-15 18:26 UTC, florence-wolfe commented on src/rbac/confirm-permission.ts
> +            `Race Log: User is not allowed to moderate race ${race.raceId}, user: ${user.username}`,
We could revert this, leave the type error (not lint error) and fix this in a future Typescript PR 🤔

2024-06-15 18:38 UTC, zoglo commented on src/components/search/autocompletion.tsx
> -    const Results = ({ results, type }) => {
As discussed, this never worked.
See: https://github.com/therungg/therun-frontend/issues/4#issuecomment-2170476055

2024-06-16 10:39 UTC, therungg requested changes
We can't merge this yet -- In the preview the tournament and race detail pages are broken. Haven't checked why, can do later.

2024-06-18 22:58 UTC, florence-wolfe commented on app/(footer)/contact/contact.tsx
> +                                <option value="">Select a category</option>
Discussed on discord and opened a new issue!

2024-06-18 23:00 UTC, florence-wolfe commented on app/live/live.tsx
> +    }, [currentlyViewing, updatedLiveDataMap]);
Removed the dependency to keep the existing production behaviour.

2024-06-18 23:06 UTC, florence-wolfe commented on src/components/live/recommended-stream.tsx
> +    const newComparisons: { [key: string]: Split } = {};
It's not lint related so I'll resolve this comment 🤷

2024-06-18 23:14 UTC, florence-wolfe commented on src/components/layout.tsx
>                                          info@therun.gg
Fixed across the application for all instances of the email including the `mailto:` links and moved it to an environment variable 👍

2024-06-19 01:03 UTC, florence-wolfe commented on app/races/components/forms/join-race-form.tsx
> +
We could probably run prettier across the code base to remove unnecessary blank lines in a separate PR

2024-06-20 22:17 UTC, zoglo commented on app/(footer)/privacy-policy/page.tsx
> +                You may always contact us by mailing at{" "}
Any use for the {" "} here?

2024-06-20 22:19 UTC, therungg commented on src/components/pagination/fetchers/races-fetcher.ts
> +    _query?: string,
doesn't this break the PaginationFetcher contract?

2024-06-20 22:19 UTC, therungg commented on src/components/patreon/patreon-styles.ts
> +                    WebkitTextFillColor: "transparent",
I think it breaks a bunch of the patron names

2024-06-20 22:19 UTC, therungg commented on src/components/run/compare/compare-splits.tsx
> +import levenshtein from "js-levenshtein";
Does this work?? I remember struggling with it a lot

2024-06-20 22:19 UTC, therungg commented on src/components/run/dashboard/golds.tsx
> +                                    const best = golds.at(-1);
oh shit this is cool

2024-06-20 22:19 UTC, therungg commented on src/components/user/stats.tsx
> +// TODO: Localize numbers and dates
i think it is client component

2024-06-20 22:25 UTC, florence-wolfe commented on app/(footer)/privacy-policy/page.tsx
> +                You may always contact us by mailing at{" "}
multiline react autoformatter things 🤷

2024-06-20 22:36 UTC, florence-wolfe commented on app/races/[race]/race-progress-graph.tsx
> +                message.type === "participant-finish" ||
The reason for the other to be extracted is _specifically_ to use that function as type predicate to narrow the type more effectively https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates

2024-06-20 22:38 UTC, florence-wolfe commented on src/components/pagination/fetchers/races-fetcher.ts
> +    _query?: string,
it can't - we're using a function with multiple arguments so the parameter naming won't matter. the `_` prefix is to signal to ts eslint that it's unused

2024-06-20 23:05 UTC, florence-wolfe commented on src/components/form/game-input.tsx
> +    const fetchSuggestions = useCallback(
Will revert this.

2024-06-20 23:05 UTC, florence-wolfe commented on src/components/run/compare/compare-splits.tsx
> +import levenshtein from "js-levenshtein";
We've tested and confirmed this doesn't break anything

2024-06-21 00:27 UTC, florence-wolfe commented on src/components/tournament/tournament-info.tsx
> +                                    >
Is this going to cause issues for large pages?

2024-06-21 00:27 UTC, florence-wolfe commented on src/components/user/stats.tsx
> +                        {getFormattedString(total.toString())}
Should this be reverted?

2024-06-21 13:39 UTC, therungg approved these changes
HUGE

2024-06-22 23:40 UTC, zoglo submitted a review, later dismissed

2024-06-22 23:40 UTC, zoglo commented on app/races/[race]/race-chat.tsx
> +const MESSAGE_TYPE = {
Should be in a separate PR imho

2024-06-24 16:24 UTC, zoglo approved these changes

2024-06-24 16:25 UTC, florence-wolfe commented on app/races/[race]/race-chat.tsx
> +const MESSAGE_TYPE = {
Will address these in a separate PR

2024-06-24 16:26 UTC, merged