feat: Feature Flags
therungg/therun-frontend pull request #29
Opened 2023-05-15 21:20 UTC by dotneB

- Support for Vercel Edge Config can be enabled if Environment Variable `EDGE_CONFIG` is present
- - Fallbacks to using environment variable when nothing is found in Edge Config
- Support for loading from environment variables

Note: Variables are prefixed by `FEATURE_FLAGS_` (ex: `FEATURE_FLAGS_MAINTENANCE_MODE`)
See #10

2023-05-16 21:54 UTC, therungg requested changes
Looking good! A few minor changes or questions. Let me know what you think, it's not a big deal :)

2023-05-16 21:54 UTC, therungg commented on lib/feature-flags.ts
> +export async function getFeatureFlag(
I would prefer to stay consistent with ES6 and use arrow functions.

`const getFeatureFlag = async (...) => {...}`
`const parseBoolean = (...) => (...)`

`export { getFeatureFlag, parseBoolean };`

Should do.

2023-05-16 21:54 UTC, therungg commented on lib/feature-flags.ts
> +    const prefixedKey = `FEATURE_FLAGS_${key.toUpperCase()}`;
1. Would it be an idea to put the prefix in a const to avoid having a magic string there?
2. I would prefer just having the `FeatureFlags` type have the types already in upper case. I don't think there's a need to define them in non-uppercase and then convert them in the function.

2023-05-16 21:55 UTC, therungg commented
Should the `EDGE_CONFIG` be set in the default `.env`, or should it only exist in PROD?

I would prefer having all possible env variables in the default `.env`, to avoid confusion. If it shouldn't be used in local, it should have a value that indicates that, but still be present imo.

2023-05-17 04:41 UTC, dotneB commented on lib/feature-flags.ts
> +    const prefixedKey = `FEATURE_FLAGS_${key.toUpperCase()}`;
1) It's pretty much already in a const. To be fair, there's very little difference, in term of "magic stringy" between
```
const prefixedKey = `FEATURE_FLAGS_${key.toUpperCase()}`;
```
and
```
const FEATURE_FLAGS_PREFIX = "FEATURE_FLAGS_";
[...]
const prefixedKey = `${FEATURE_FLAGS_PREFIX}${key.toUpperCase()}`;
```
If you prefer I had it initially as a function in the file, but since it was only used in one place I went with the one-liner. But I had it like this before
```
const prefixKey = (key: string) => `FEATURE_FLAGS_${key.toUpperCase()}`;
[...]
const prefixedKey = prefixKey(key);
```

2) I can change the FeatureFlags type to be uppercase. But removing the toUpperCase means that we always absolutely trust progs to never forget the convention and always catch these errors in PRs before merge. I'd tend to lean more toward leaving it

2023-05-17 04:46 UTC, dotneB commented
> Should the `EDGE_CONFIG` be set in the default `.env`, or should it only exist in PROD?
> 
> I would prefer having all possible env variables in the default `.env`, to avoid confusion. If it shouldn't be used in local, it should have a value that indicates that, but still be present imo.

There are limits/cost to having Edge Configs on vercel, so that's the only reason why I could see not wanting to expose it to local. Because of the number of refreshes and tests we do. And since there are limits and cost, I prefer assuming this doesn't need to be activated to function, that's why it falls back to using Env variables.

But I added it to the default .env and handle the case where it's an empty string as disabled.

2023-05-17 08:37 UTC, therungg approved these changes

2023-05-17 08:38 UTC, merged

2023-05-17 08:38 UTC, therungg commented
Merged, thanks so much, @dotneB!