Solved button disappearing issue #289
therungg/therun-frontend pull request #290
Opened 2024-11-02 18:01 UTC by Rakshit-gen

![image](https://github.com/user-attachments/assets/86a49afa-915d-43e1-b843-fa6631d90bcc)

![image](https://github.com/user-attachments/assets/8095ac41-a021-493e-b846-a370918e246c)

for both the themes

2024-11-02 18:24 UTC, zoglo requested changes

2024-11-02 18:24 UTC, zoglo commented on app/patron/patreon-info.tsx
> +                            rel="noopener"
Change seems unrelated to the issue?

2024-11-02 18:24 UTC, zoglo commented on app/patron/patreon-info.tsx
> +                style={{ fill: "var(--bs-primary)" }}
I'd rather have a custom class like this:
```css
button:hover path {
    fill: var(--bs-body-bg)
}
```
![image](https://github.com/user-attachments/assets/8fab13cb-fa2e-4c32-8255-d82dd60c7f6e)

We shouldn't change the gold bunny (gold splits) to just green splits :)

2024-11-02 18:24 UTC, zoglo commented on app/home/homepage.tsx
> +                                className="btn-lg me-sm-3 px-3 w-160p h-3r fw-medium hover:text-white"
We ain't using tailwind but bootstrap 🤔

2024-11-03 05:25 UTC, Rakshit-gen commented on app/patron/patreon-info.tsx
> +                            rel="noopener"
Undid the change

2024-11-03 05:25 UTC, Rakshit-gen commented on app/patron/patreon-info.tsx
> +                style={{ fill: "var(--bs-primary)" }}
How do I do this, I am a bit confused on how to add styles in the repository.

2024-11-03 05:26 UTC, Rakshit-gen commented on app/home/homepage.tsx
> +                                className="btn-lg me-sm-3 px-3 w-160p h-3r fw-medium hover:text-white"
Added it by mistake while testing, resolved this.

2024-11-03 10:31 UTC, zoglo requested changes

2024-11-03 10:31 UTC, zoglo commented on app/patron/patreon-info.tsx
> +                style={{ fill: "var(--bs-primary)" }}
We are using Bootstrap 5.3, this + custom are setup in src/styles and compiles on the fly if you are running the server.

2024-11-03 10:31 UTC, zoglo commented on package-lock.json
Deleting dependencies seems unrelated? We should ever use npm ci when installing something to not modify it (cross operating system)

2024-11-03 10:31 UTC, zoglo commented on app/home/homepage.tsx
> +                        <Link href="/abougt">
Newly added error

2024-12-13 19:32 UTC, closed without merging